---
- name: Download WordPress
  get_url: 
    url: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz" 
    dest: "/srv/wordpress-{{ wp_version }}.tar.gz"
    sha256sum: "{{ wp_sha256sum }}"

- name: Extract archive
  command: "/bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress"
  args:
    chdir: /srv

- name: Add group "wordpress"
  group: 
    name: wordpress

- name: Add user "wordpress"
  user:
    name: wordpress 
    group: wordpress 
    home: "/srv/wordpress/"

- name: get API information for wp-config
  uri:
    url: "https://api.wordpress.org/secret-key/1.1/salt/"
    return_content: True
    method: GET
  register: wp_salt

- name: Create WordPress database
  mysql_db: 
    name: "{{ wp_db_name }}" 
    state: present

- name: Create WordPress database user
  mysql_user: 
    name: "{{ wp_db_user }}" 
    password: "{{ wp_db_password }}" 
    priv: "{{ wp_db_name }}.*:ALL" 
    host: 'localhost' 
    state: present

- name: Copy WordPress config file
  template: 
    src: wp-config.php 
    dest: /srv/wordpress/

- name: Change ownership of WordPress installation
  file: 
    path: /srv/wordpress/ 
    owner: wordpress 
    group: wordpress 
    state: directory 
    recurse: yes

- name: install SEManage
  yum:
    name: policycoreutils-python
    state: present

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Set the SELinux policy for the Wordpress directory
  community.general.sefcontext:
    target: "/srv/wordpress(/.*)?"
    setype: httpd_sys_content_t
    ignore_selinux_state: yes
    state: present
    
- name: Set the SELinux policy for wp-config.phpy
  community.general.sefcontext:
    target: "/srv/wordpress/wp-config\\.php"
    setype: httpd_sys_script_exec_t
    ignore_selinux_state: yes
    state: present

- name: Set the SELinux policy for wp-content directory
  community.general.sefcontext:
    target: "/srv/wordpress/wp-content(/.*)?"
    setype: httpd_sys_rw_content_t
    ignore_selinux_state: yes
    state: present

- name: Set the SELinux policy for the *.php files
  community.general.sefcontext:
    target: "/srv/wordpress/.*\\.php"
    setype: httpd_sys_script_exec_t
    ignore_selinux_state: yes
    state: present

- name: Set the SELinux policy for the Upgrade directory
  community.general.sefcontext:
    target: "/srv/wordpress/wp-content/upgrade(/.*)?"
    setype: httpd_sys_rw_content_t
    ignore_selinux_state: yes
    state: present

- name: Set the SELinux policy for the Uploads directory
  community.general.sefcontext:
    target: "/srv/wordpress/wp-content/uploads(/.*)?"
    setype: httpd_sys_rw_content_t
    ignore_selinux_state: yes
    state: present

- name: Set the SELinux policy for the wp-includes php files
  community.general.sefcontext:
    target: "/srv/wordpress/wp-includes/.*\\.php"
    setype: httpd_sys_script_exec_t
    ignore_selinux_state: yes
    state: present

- name: set the SELinux on all the Files
  command: restorecon -Rv /srv/wordpress

- name: Start php-fpm Service
  service: 
    name: php-fpm 
    state: started 
    enabled: yes
