---
- name: Install and configure Apache on Linux
  hosts: linux_hosts

  vars:
    httpd_conf_file: '/etc/httpd/conf/httpd.conf'
 
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: installed

    - name: Change ServerAdmin email
      lineinfile:
        path: "{{ httpd_conf_file }}"
        regexp: '^ServerAdmin '
        line: ServerAdmin ansible@automationbasics.net
        backrefs: yes

    - name: Change Default port
      lineinfile:
        path: "{{ httpd_conf_file }}"
        regexp: '^Listen '
        line: Listen 8080
        backrefs: yes

    - name: Overwrite index.html file with local copy
      template:
        src: index.html.j2
        dest: '/var/www/html/index.html'
      register: index_file

    - name: Set service startup mode to auto and ensure it is restarted
      service:
        name: httpd
        enabled: yes
        state: restarted
      when: index_file.changed

