---
- name: Instead of setting value there's also option to set a fact
  set_fact:
    yum_reposd_dir: "/etc/yum.repos.d"
    rpm_gpg_dir: "/etc/pki/rpm-gpg"

- name: Copy the NGINX repository definition
  ansible.builtin.copy:
    src: nginx.repo 
    dest: "{{ yum_reposd_dir }}"

- name: Copy the EPEL repository definition
  ansible.builtin.copy:
    src: epel.repo 
    dest: "{{ yum_reposd_dir }}"

- name: Copy the REMI repository definition
  ansible.builtin.copy: 
    src: remi.repo 
    dest: "{{ yum_reposd_dir }}"

- name: Create the GPG key for NGINX
  ansible.builtin.copy:
    src: RPM-GPG-KEY-NGINX 
    dest: "{{ rpm_gpg_dir }}"

- name: Create the GPG key for EPEL
  ansible.builtin.copy:
    src: RPM-GPG-KEY-EPEL-7 
    dest: "{{ rpm_gpg_dir }}"

- name: Create the GPG key for REMI
  ansible.builtin.copy: 
    src: RPM-GPG-KEY-remi 
    dest: "{{ rpm_gpg_dir }}"
  
- name: Install Firewalld
  yum: 
    name: firewalld 
    state: present

- name: Firewalld service state
  service: 
    name: firewalld 
    state: started 
    enabled: yes
